anestudy/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path("", views.index),
    path("tags/<slug:slug>", views.tags),
    path("<slug:pk>/", views.posted_article),
    path("posted_article/<slug:pk>/", views.posted_article),
    path("<slug:postarticle_id>/edit/postarticle/", views.edit_post),
    path("tags/add/postarticle", views.add_post, name="add_post"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from anestudy import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('omh_index/', views.omh_index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('posted_articles/', views.posted_articles),
    path('posted_articles_top/', views.posted_articles_top),
    path('anestudy/', include('anestudy.urls')),
    path('signup/', views.signup),
    path('mypage/', views.MypageView.as_view()),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('posted_articles_top/add/postarticle', views.add_post, name='add_post'),
    path('edit/postarticle/<int:postarticle_id>/', views.edit_post, name='edit_post')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anestudy/models/account.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


# --- OneToOneField を同時に作成 ---
from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs["created"]:
        from anestudy.models.profile import Profile

        Profile.objects.create(user=kwargs["instance"])


# --- OneToOneField を同時に作成 ---

anestudy/models/blog.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.aggregates import Count
from django.utils.text import slugify


class Tag(models.Model):
    slug = models.CharField(primary_key=True, unique=True, max_length=20)
    name = models.CharField(unique=True, max_length=20)
    category = models.CharField(unique=False, max_length=20, null=True)
    category2 = models.CharField(unique=False, max_length=20, null=True)

    def __str__(self):
        return self.slug


class Category(models.Model):
    slug = models.CharField(primary_key=True, unique=True, max_length=20)
    name = models.CharField(unique=True, max_length=20)

    def __str__(self):
        return self.slug


class Article(models.Model):
    title = models.CharField(default="", max_length=30)
    text = RichTextField(blank=True, null=True)
    author = models.CharField(default="", max_length=30)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    count = models.IntegerField(
        default=0,
    )
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ManyToManyField(Category, blank=True)


class PostArticle(models.Model):
    title = models.CharField(default="", max_length=30)
    text = RichTextUploadingField(blank=True, null=True)
    author = models.CharField(default="", max_length=30)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    count = models.IntegerField(
        default=0,
    )
    tags = models.ManyToManyField(Tag, blank=True)
    slug = models.SlugField(default="", blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def save(self):
        self.slug = slugify(self.title)
        super(PostArticle, self).save()

    def __str__(self):
        return "%s" % self.title


class Comment(models.Model):
    comment = models.TextField(default="", max_length=500)
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article = models.ForeignKey(PostArticle, on_delete=models.CASCADE)

anestudy/models/profile.py
import os

from django.contrib.auth import get_user_model
from django.db import models


def upload_image_to(instance, filename):
    user_id = str(instance.user.id)
    return os.path.joib("static", "image", user_id, filename)


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(), unique=True, on_delete=models.CASCADE, primary_key=True
    )

    username = models.CharField(default="匿名ユーザー", max_length=30)

    zipcode = models.CharField(default="", max_length=8)

    prefecture = models.CharField(default="", max_length=6)

    city = models.CharField(default="", max_length=100)

    address = models.CharField(default="", max_length=200)

    image = models.ImageField(default="", blank=True, upload_to=upload_image_to)

anestudy/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import fields

from anestudy.models.blog import Comment, PostArticle
from anestudy.models.profile import Profile


class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ("email",)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "username",
            "zipcode",
            "prefecture",
            "city",
            "address",
            "image",
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)


class PostForm(forms.ModelForm):
    class Meta:
        model = PostArticle
        fields = (
            "title",
            "text",
            "author",
            "tags",
            "categories",
        )

anestudy/views.py
import os

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from anestudy.forms import CommentForm, PostForm, ProfileForm, UserCreationForm
from anestudy.models.blog import Article, Comment, PostArticle, Tag


def index(request):
    ranks = PostArticle.objects.order_by("-count")[:4]
    latests = PostArticle.objects.order_by("-created_at")[:4]
    objs = PostArticle.objects.all()[:3]
    context = {
        "title": "omh-site",
        "articles": objs,
        "ranks": ranks,
        "latests": latests,
    }
    return render(request, "anestudy/index.html", context)


class Login(LoginView):
    template_name = "anestudy/auth.html"

    def form_valid(self, form):
        messages.success(self.request, "ログイン完了")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "ログインエラー")
        return super().form_invalid(form)


def signup(request):
    context = {}
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.is_active = False
            user.save()
            # ログインさせる
            login(request, user)
            messages.success(request, "登録完了")
            return redirect("/")
    return render(request, "anestudy/auth.html", context)


class MypageView(LoginRequiredMixin, View):
    context = {}

    def get(self, request):
        return render(request, "anestudy/mypage.html", self.context)

    def post(self, request):
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, "更新完了")
        return render(request, "anestudy/mypage.html", self.context)

def posted_articles(request):
    objs = PostArticle.objects.all()
    paginator = Paginator(objs, 100)
    page_number = request.GET.get("page")
    context = {
        "page_title": "当院の麻酔",
        "page_obj": paginator.get_page(page_number),
        "page_number": page_number,
    }
    return render(request, "anestudy/posted_articles.html", context)


def posted_articles_top(request):
    tags = Tag.objects.all()
    context = {
        "top_tags": tags,
    }
    return render(request, "anestudy/posted_articles_top.html", context)


def article(request, pk):
    obj = Article.objects.get(pk=pk)
    if request.method == "POST":
        if request.POST.get("like_count", None):
            obj.count += 1
            obj.save()
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.article = obj
                comment.save()
    comments = Comment.objects.filter(article=obj)
    context = {
        "article": obj,
        "comments": comments,
    }
    return render(request, "anestudy/article.html", context)


def posted_article(request, pk):
    obj = PostArticle.objects.get(pk=pk)
    if request.method == "POST":
        if request.POST.get("like_count", None):
            obj.count += 1
            obj.save()
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.article = obj
                comment.save()
    comments = Comment.objects.filter(article=obj)
    context = {
        "posted_article": obj,
        "comments": comments,
    }
    return render(request, "anestudy/posted_article.html", context)


def tags(request, slug):
    tag = Tag.objects.get(slug=slug)
    objs = tag.postarticle_set.all()

    paginator = Paginator(objs, 2)
    page_number = request.GET.get("page")
    context = {
        "page_title": tag.name,
        "page_obj": paginator.get_page(page_number),
        "page_number": page_number,
    }
    return render(request, "anestudy/posted_articles_tag.html", context)


def add_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            postarticle_item = form.save(commit=False)
            postarticle_item.save()
            return redirect("/")
    else:
        form = PostForm()
    return render(request, "anestudy/postarticle.html", {"form": form})


def edit_post(request, postarticle_id=None):
    postarticle_item = get_object_or_404(PostArticle, id=postarticle_id)
    form = PostForm(request.POST or None, instance=postarticle_item)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, "anestudy/postarticle.html", {"form": form})


def omh_index(request):
    return render(request, "anestudy/omh_index.html")

templates/anestudy/base.html
<!doctype html>
<html lang="ja">
 
<head>
    {% include 'anestudy/snippets/head.html' %}
</head>
 
<body>
    {% include 'anestudy/snippets/header.html' %}
    {% include 'anestudy/snippets/messages.html' %}

    {% block content %}
    {% endblock %}
    
    {% include 'anestudy/snippets/footer.html' %}
</body>
 
</html>

templates/anestudy/base_auth.html
<!doctype html>
<html lang="ja">
  <head>
        {% include 'anestudy/snippets/head.html' %}
  </head>
  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">
 
    {% block content %}
    {% endblock %}
    
  </body>
</html>

templates/anestudy/mypage.html
{% extends 'anestudy/base.html' %}
 
{% block content %}
 
<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            マイページ
        </h3>
 
        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'anestudy/snippets/profile_image.html' %}

            


            <div class="col-12">
                <label class="form-label">ユーザー名（公開されます）</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="煉獄 杏寿郎" value="{{ user.profile.username }}">
              </div>
 
              <div class="col-md-2">
                <label class="form-label">郵便番号</label>
                <input type="text" class="form-control" id="id_zipcode" name="zipcode" value="{{ user.profile.zipcode }}">
              </div>
              <div class="col-md-4">
                <label class="form-label">都道府県</label>
                <select id="id_prefecture" name="prefecture" class="form-select">
                  <option selected>選択...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="col-md-6">
                <label class="form-label">市区</label>
                <input type="text" class="form-control" id="id_city" name="city" value="{{ user.profile.city }}">
              </div>
              
            <div class="col-12">
              <label class="form-label">住所</label>
              <input type="text" class="form-control" id="id_address" name="address" placeholder="" value="{{ user.profile.address }}">
            </div>
 
            <div class="col-12">
              <button type="submit" class="btn btn-success">保存</button>
            </div>
          </form>
 
        </div>
 
        {% include 'anestudy/snippets/sidebar.html' %}
 
    </div>
</main>
 
 
{% endblock %}

templates/anestudy/omh_index 2.html
{% extends 'anestudy/base.html' %}

{% block content %}

{% load static %}

<main class="container">
    <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white"
    style="background-image: url({% static 'anestudy/omh-top1.png' %})"; height: 100vh>
        <div class="mask" style="background-color: rgba(192, 192, 192, 0.9);">
            <div class="justify-content-center align-items-center h-100">
                <h3 class="text-body mb-4 pt-5">大垣市民病院麻酔科</h3>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-3">
                            はじめに
                        </h3>
                        <p>
                            30年以上の歴史を引き継いで、2015年より現行体制がスタートしました。<br>
                            2022年1月現在9名の若手麻酔科医が手術室と集中治療室を含む中央診療部門を担っています。<br>
                            急性期治療を担う仲間を随時募集しています。<br>
                            いつでも、ご連絡ください。<br><br>
                            連絡先: <a href="mailto:masui@omh.ogaki.gifu.jp">masui@omh.ogaki.gifu.jp</a><br>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            麻酔
                        </h3>
                        <p>
                            麻酔に関する有資格者が在籍し、サブスペシャリティも習得できます。<br>
                            移植手術を除き、ほぼ全ての麻酔を経験する事ができます。<br>
                            <h5 class="text-decoration-underline pb-4">
                                特記すべき麻酔
                            </h5>
                            <div class="row justify-content-center">
                                <div class="col-md-4 mb-4 text-body text-left">
                                    ・小児心臓外科の麻酔<br>
                                    ・外傷 ( 熱傷を含む ) の麻酔<br>
                                    ・TAVI を含む血管内治療の麻酔<br>
                                    ・ブロックによる区域麻酔<br>
                                    ・気管支ステントの麻酔<br>
                                    ・食道癌や肝臓癌などの侵襲が大きな麻酔
                                </div>
                            </div>
                        </p>
                        <p>これらの麻酔を全て経験できる施設は、あまりありません。<br>
                            週 2 回の抄読会と勉強会で最新の動向を catch up しています。<br>
                            evidence に基づいた知識と経験値を得ることができます。<br>
                            コメディカルが意欲的で、レベルが非常に高いことも心強い特記事項と言えます。
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            集中治療
                        </h3>
                        <p>
                            手術室麻酔だけではなく、集中治療を勉強できる環境整備にも取り組んでいます。<br>
                            現在の集中治療室は、主治医管理となっています。<br>
                            しかし、ほとんどの主治医は集中治療の経験がなく、手術中や処置中で対応も難しい状態が続いていました。<br>
                            2017年にスタートしたばかりですが、多職種の「チーム」で治療できる体制を強化しています。<br>
                            看護師、臨床工学技士、薬剤師、理学療法士、言語聴覚士、管理栄養士がチームに参加しており、毎日ディスカッションが行われています。<br>
                            敗血症、ARDS、IMPELLA、ECMO、血液浄化療法など、幅広く学べます。<br><br>
                            <a href="https://project-linked.com/linkedplus/linked_vol32/ogakishimin/page01/">集中治療室での取り組み</a>
                        </p>


                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            専門医プログラム
                        </h3>
                        <p>
                            「大垣市民病院麻酔科専門研修プログラム」が 2018 年度から採用されています。<br>
                            <br>
                            <h5 class="text-decoration-underline pb-4">このプログラムのメリットは、</h5>
                            <div class="row justify-content-center">
                                <div class="col-md-8 mb-4 text-body text-left">
                                    ・医局の枠組を超えたプログラムであること。<br>
                                    ・名古屋大学・藤田医科大学・岐阜大学が関連病院であること。<br>
                                    ・勉強したい施設や項目があれば、科をあげて応援し、送り出す準備があること。<br>
                                    ・もちろん、仕事とプライベートのバランスなど、個々の希望に最大限寄り添う事を約束します。<br>
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-10 mb-4 text-body ">
                        <h3 class="pb-4">
                            メンバー紹介
                        </h3>
                        <p class="text-left">
                            2015.04- 高須昭彦、加藤規子、伊東遼平、横山達郎<br>
                            2017.04- 高須昭彦、伊東遼平、横山達郎<br>
                            2017.10- 高須昭彦、伊東遼平、柴田紘葉、和田玲太朗（横山達郎 : 名古屋大学）<br>
                            2018.10- 高須昭彦、柴田紘葉、横山達郎、和田玲太朗（伊東遼平 : 名古屋大学）<br>
                            2019.04- 高須昭彦、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗（伊東遼平 : 名古屋大学）<br>
                            2019.10- 高須昭彦、伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗<br>
                            2020.04- 伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、坂口大剛（吉川晃士朗 : 藤田医科大学）<br>
                            2021.04- 伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗、坂口大剛、竹内基、谷村洋輔<br>
                        </p>
                        <p class="pl-4 text-left">
                            伊東遼平 : 麻酔科学会指導医、心臓血管麻酔学会専門医、区域麻酔学会指導医、小児麻酔学会認定医、J-RACE(2019)、ICD<br>
                            柴田紘葉 : 麻酔科学会専門医、心臓血管麻酔学会専門医<br>
                            横山達郎 : 麻酔科学会専門医、心臓血管麻酔学会専門医、ICD、集中治療学会専門医(2022年度-)<br>
                            和田玲太朗 : 麻酔科学会専門医、心臓血管麻酔学会専門医(2022年度-)<br>
                            岡本文乃 : 麻酔科学会専門医(2022年度-)<br>
                            吉川晃士朗 : 麻酔科専攻医<br>
                            坂口大剛 : 麻酔科専攻医<br>
                            竹内基 : 麻酔科専攻医<br>
                            谷村洋輔 : 麻酔科専攻医<br>
                        </p>

                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

{% endblock %}

templates/anestudy/omh_index.html
{% extends 'anestudy/base.html' %}

{% block content %}

{% load static %}

<main class="container">
    <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white"
    style="background-image: url({% static 'anestudy/omh-top1.png' %})"; height: 100vh>
        <div class="mask" style="background-color: rgba(192, 192, 192, 0.9);">
            <div class="justify-content-center align-items-center h-100">
                <h3 class="text-body mb-4 pt-5">大垣市民病院麻酔科</h3>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-3">
                            はじめに
                        </h3>
                        <p>
                            30年以上の歴史を引き継いで、2015年より現行体制がスタートしました。<br>
                            2022年1月現在9名の若手麻酔科医が手術室と集中治療室を含む中央診療部門を担っています。<br>
                            急性期治療を担う仲間を随時募集しています。<br>
                            いつでも、ご連絡ください。<br><br>
                            連絡先: <a href="mailto:masui@omh.ogaki.gifu.jp">masui@omh.ogaki.gifu.jp</a><br>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            麻酔
                        </h3>
                        <p>
                            麻酔に関する有資格者が在籍し、サブスペシャリティも習得できます。<br>
                            移植手術を除き、ほぼ全ての麻酔を経験する事ができます。<br>
                            <h5 class="text-decoration-underline pb-4">
                                特記すべき麻酔
                            </h5>
                            <div class="row justify-content-center">
                                <div class="col-md-4 mb-4 text-body text-left">
                                    ・小児心臓外科の麻酔<br>
                                    ・外傷 ( 熱傷を含む ) の麻酔<br>
                                    ・TAVI を含む血管内治療の麻酔<br>
                                    ・ブロックによる区域麻酔<br>
                                    ・気管支ステントの麻酔<br>
                                    ・食道癌や肝臓癌などの侵襲が大きな麻酔
                                </div>
                            </div>
                        </p>
                        <p>これらの麻酔を全て経験できる施設は、あまりありません。<br>
                            週 2 回の抄読会と勉強会で最新の動向を catch up しています。<br>
                            evidence に基づいた知識と経験値を得ることができます。<br>
                            コメディカルが意欲的で、レベルが非常に高いことも心強い特記事項と言えます。
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            集中治療
                        </h3>
                        <p>
                            手術室麻酔だけではなく、集中治療を勉強できる環境整備にも取り組んでいます。<br>
                            現在の集中治療室は、主治医管理となっています。<br>
                            しかし、ほとんどの主治医は集中治療の経験がなく、手術中や処置中で対応も難しい状態が続いていました。<br>
                            2017年にスタートしたばかりですが、多職種の「チーム」で治療できる体制を強化しています。<br>
                            看護師、臨床工学技士、薬剤師、理学療法士、言語聴覚士、管理栄養士がチームに参加しており、毎日ディスカッションが行われています。<br>
                            敗血症、ARDS、IMPELLA、ECMO、血液浄化療法など、幅広く学べます。<br><br>
                            <a href="https://project-linked.com/linkedplus/linked_vol32/ogakishimin/page01/">集中治療室での取り組み</a>
                        </p>


                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-4 text-body">
                        <h3 class="pb-4">
                            専門医プログラム
                        </h3>
                        <p>
                            「大垣市民病院麻酔科専門研修プログラム」が 2018 年度から採用されています。<br>
                            <br>
                            <h5 class="text-decoration-underline pb-4">このプログラムのメリットは、</h5>
                            <div class="row justify-content-center">
                                <div class="col-md-8 mb-4 text-body text-left">
                                    ・医局の枠組を超えたプログラムであること。<br>
                                    ・名古屋大学・藤田医科大学・岐阜大学が関連病院であること。<br>
                                    ・勉強したい施設や項目があれば、科をあげて応援し、送り出す準備があること。<br>
                                    ・もちろん、仕事とプライベートのバランスなど、個々の希望に最大限寄り添う事を約束します。<br>
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-10 mb-4 text-body ">
                        <h3 class="pb-4">
                            メンバー紹介
                        </h3>
                        <p class="text-left">
                            2015.04- 高須昭彦、加藤規子、伊東遼平、横山達郎<br>
                            2017.04- 高須昭彦、伊東遼平、横山達郎<br>
                            2017.10- 高須昭彦、伊東遼平、柴田紘葉、和田玲太朗（横山達郎 : 名古屋大学）<br>
                            2018.10- 高須昭彦、柴田紘葉、横山達郎、和田玲太朗（伊東遼平 : 名古屋大学）<br>
                            2019.04- 高須昭彦、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗（伊東遼平 : 名古屋大学）<br>
                            2019.10- 高須昭彦、伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗<br>
                            2020.04- 伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、坂口大剛（吉川晃士朗 : 藤田医科大学）<br>
                            2021.04- 伊東遼平、柴田紘葉、横山達郎、和田玲太朗、岡本文乃、吉川晃士朗、坂口大剛、竹内基、谷村洋輔<br>
                        </p>
                        <p class="pl-4 text-left">
                            伊東遼平 : 麻酔科学会指導医、心臓血管麻酔学会専門医、区域麻酔学会指導医、小児麻酔学会認定医、J-RACE(2019)、ICD<br>
                            柴田紘葉 : 麻酔科学会専門医、心臓血管麻酔学会専門医<br>
                            横山達郎 : 麻酔科学会専門医、心臓血管麻酔学会専門医、ICD、集中治療学会専門医(2022年度-)<br>
                            和田玲太朗 : 麻酔科学会専門医、心臓血管麻酔学会専門医(2022年度-)<br>
                            岡本文乃 : 麻酔科学会専門医(2022年度-)<br>
                            吉川晃士朗 : 麻酔科専攻医<br>
                            坂口大剛 : 麻酔科専攻医<br>
                            竹内基 : 麻酔科専攻医<br>
                            谷村洋輔 : 麻酔科専攻医<br>
                        </p>

                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

{% endblock %}

templates/anestudy/postarticle 2.html
{% extends 'anestudy/base.html' %}

{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>

{% endblock %}

templates/anestudy/postarticle.html
{% extends 'anestudy/base.html' %}

{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>

{% endblock %}

templates/anestudy/posted_articles 2.html
{% extends 'anestudy/base.html' %}

{% block content %}

<main class="container">
    <div class="row row-cols-3" style="height: 300px">
        {% for obj in page_obj %}
            <div class="d-flex align-items-center justify-content-center bg-light border border-dark">
                <a href="/anestudy/posted_article/{{obj.id}}/" class="">{{ obj.title }}</a>
            </div>
        {% endfor %}
    </div>
</main>

{% endblock %}